set -g mouse on
set -g history-limit 99999
set -g base-index 1

bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

bind z display-popup -d "#{pane_current_path}" -w 75% -h 75% -E "zsh"
bind d display-menu -T "#[align=center]Dotfiles" -x C -y C \
  ".zshrc" z "display-popup -w 80% -h 80% -E 'nvim ~/.zshrc'" \
  ".tmux.conf" t "display-popup -w 80% -h 80% -E 'nvim ~/.config/tmux/tmux.conf'" \
  ".alacritty.toml" z "display-popup -w 80% -h 80% -E 'nvim ~/.config/alacritty/alacritty.toml'" \
  ".alacritty.keymaps" z "display-popup -w 80% -h 80% -E 'nvim ~/.config/alacritty/keybindings.toml'" \
  ".nvim.lazy.lua" z "display-popup -w 80% -h 80% -E 'nvim ~/.config/nvim/lua/config/lazy.lua'" \
  ".nvim.lazy.keymaps" z "display-popup -w 80% -h 80% -E 'nvim ~/.config/nvim/lua/config/keymaps.lua'" 
bind g display-popup -d "#{pane_current_path}" -w 90% -h 90% -E "lazygit"

set-option -sa terminal-overrides ",xterm*:Tc"
set-option -g status-position top
set -g default-terminal "tmux-256color"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Configure Tmux-Yank to NOT clear selection on mouse drag
set -g @yank_action 'copy-pipe-no-clear'
set -g @yank_with_mouse off

# Catppuccin theme config
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_window_text "#W"
set -g @catppuccin_status_background "#1e1e2e"

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""

# Show these modules on the right (in theme colors)
set -g @catppuccin_status_modules "#{E:@catppuccin_status_application}"
set -g status-right "#{E:@catppuccin_status_application}" 
set -ag status-right "#{E:@catppuccin_status_session}"

#run-shell "~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux"
# set vi-mode
set-window-option -g mode-keys vi

# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
unbind -T copy-mode-vi MouseDragEnd1Pane

# TPM
run "~/.config/tmux/plugins/tpm/tpm"
